### ISSUE TITLE
Error validating SQL migration filenames

### ISSUE THREAD

**Issue by cristiammercado** [flyway/flyway#3482]
###### Which version and edition of Flyway are you using?

Flyway MySQL 9.0.1, Community edition 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin for MySQL

```
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-mysql</artifactId>
    <version>9.0.1</version>
</dependency>

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.29</version>
</dependency>
```

###### Which database are you using? (Type & version)

MySQL 8.0.29

###### Which operating system are you using?

Windows, Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have a Maven project with migrations in SQL files located in the `src/main/resources/migrations` folder. I have always generated a fat jar when building. Version 8.5.13 detected all the sql migration files without problems and executed the migrations, but from version 9.0.0 (and it also appears in version 9.0.1) there was a change in the [`flyway-core/src class /main/java/org/flywaydb/core/internal/resource/ResourceNameParser.java:134`](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resource/ResourceNameParser.java#L134) clas which does not seem to properly read the configured prefix for migrations. 

**NOTE:** The error only occurs when I run the jar file. When I run the app directly in my IDE it works fine. I clarify that I have not changed another dependency nor the way the code is compiled and generates the fat jar.

This generates an error of type `org.flywaydb.core.api.FlywayException: Invalid SQL filenames found` with all migration files.

![image](https://user-images.githubusercontent.com/4806666/179321076-e609cde9-fe8b-44dd-ac29-fceacb0808e4.png)

```
[2022-07-15 17:28:40.692] INFO  [main] [Slf4jLog.java:37] Flyway Community Edition 9.0.1 by Redgate
[2022-07-15 17:28:40.693] INFO  [main] [Slf4jLog.java:37] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.0.1
[2022-07-15 17:28:40.693] INFO  [main] [Slf4jLog.java:37] 
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] AWS SDK available: false
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Google Cloud Storage available: false
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Scanning for classpath resources at 'classpath:db/callback' ...
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Determining location urls for classpath:db/callback using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93 ...
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Unable to resolve location classpath:db/callback.
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Scanning for classpath resources at 'classpath:migrations' ...
[2022-07-15 17:28:40.694] DEBUG [main] [Slf4jLog.java:33] Determining location urls for classpath:migrations using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93 ...
[2022-07-15 17:28:40.695] DEBUG [main] [Slf4jLog.java:33] Scanning URL: jar:file:/D:/projects/[hidden]/target/[hidden].jar!/migrations
[2022-07-15 17:28:40.695] DEBUG [main] [Slf4jLog.java:33] JBoss VFS v2 available: false
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202007260__create_main_tables.sql
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202007270__update_third_parties_tables.sql
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202007280__update_users_table.sql
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202008230__update_taxes_table.sql
[2022-07-15 17:28:40.707] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202008240__update_stores_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202008300__create_templates_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202009010__update_templates_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202009090__update_stores_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202009091__update_app_installations_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202009100__update_services_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202011020__create_stats_tables.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202012290__update_email_messages_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202012300__update_invoices_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202012310__update_credit_notes_table.sql
[2022-07-15 17:28:40.708] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202101060__update_templates_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202101090__delete_unused_tables.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202101091__update_templates_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202101110__update_credit_notes_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202101130__update_templates_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202102100__update_email_messages_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202102130__update_invoices_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202102140__update_stats_templates_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103180__update_app_web_updates_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103250__update_taxes_table.sql
[2022-07-15 17:28:40.709] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103280__update_third_parties_table.sql
[2022-07-15 17:28:40.710] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103290__update_online_payments_tables.sql
[2022-07-15 17:28:40.710] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103300__delete_updates_tables.sql
[2022-07-15 17:28:40.710] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202103301__update_invoices_table.sql
[2022-07-15 17:28:40.710] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104010__delete_app_templates_table.sql
[2022-07-15 17:28:40.711] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104020__update_auth_tables.sql
[2022-07-15 17:28:40.711] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104030__update_invoice_resolutions_table.sql
[2022-07-15 17:28:40.711] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104110__update_invoices_detail_table.sql
[2022-07-15 17:28:40.711] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104160__update_auth_tables.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104170__credit_notes_tables.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104210__update_cash_counts_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104230__update_purchase_orders_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202104240__update_remissions_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202105260__update_email_messages_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202106030__update_app_web_updates_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202106031__update_app_stats_tables.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202106290__update_email_messages_table.sql
[2022-07-15 17:28:40.712] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202107080__update_credit_notes_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202107110__update_products_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202107220__update_cash_receipts_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202108200__update_credit_notes_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202108220__update_cash_counts_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202111070__update_unused_tables.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202111090__update_contacts_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Found resource: migrations/v202205100__update_web_form_table.sql
[2022-07-15 17:28:40.713] DEBUG [main] [Slf4jLog.java:33] Scanning for classes at classpath:migrations
[2022-07-15 17:28:40.715] DEBUG [main] [Slf4jLog.java:33] Filtering out resource: migrations/ (filename: )
[2022-07-15 17:28:40.715] DEBUG [main] [Slf4jLog.java:33] Validating v202103290__update_online_payments_tables.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202103301__update_invoices_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202101060__update_templates_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202103250__update_taxes_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202104210__update_cash_counts_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202104240__update_remissions_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202008240__update_stores_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202107110__update_products_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202103300__delete_updates_tables.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202007260__create_main_tables.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202108200__update_credit_notes_table.sql
[2022-07-15 17:28:40.716] DEBUG [main] [Slf4jLog.java:33] Validating v202103180__update_app_web_updates_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202104230__update_purchase_orders_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202101110__update_credit_notes_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202009010__update_templates_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202105260__update_email_messages_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202008300__create_templates_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202101091__update_templates_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202011020__create_stats_tables.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202012300__update_invoices_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202107220__update_cash_receipts_table.sql
[2022-07-15 17:28:40.717] DEBUG [main] [Slf4jLog.java:33] Validating v202007280__update_users_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202009091__update_app_installations_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202012310__update_credit_notes_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202111070__update_unused_tables.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202009090__update_stores_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202102130__update_invoices_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202102140__update_stats_templates_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202104030__update_invoice_resolutions_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202101090__delete_unused_tables.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202104110__update_invoices_detail_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202106031__update_app_stats_tables.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202106030__update_app_web_updates_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202205100__update_web_form_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202008230__update_taxes_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202108220__update_cash_counts_table.sql
[2022-07-15 17:28:40.718] DEBUG [main] [Slf4jLog.java:33] Validating v202009100__update_services_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202102100__update_email_messages_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202007270__update_third_parties_tables.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202104020__update_auth_tables.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202104170__credit_notes_tables.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202104010__delete_app_templates_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202103280__update_third_parties_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202104160__update_auth_tables.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202106290__update_email_messages_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202107080__update_credit_notes_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202111090__update_contacts_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202012290__update_email_messages_table.sql
[2022-07-15 17:28:40.719] DEBUG [main] [Slf4jLog.java:33] Validating v202101130__update_templates_table.sql
[2022-07-15 17:28:40.720] INFO  [main] [AppLauncher.java:101] Error starting vertx application
org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Unrecognised migration name format: v202103290__update_online_payments_tables.sql
Unrecognised migration name format: v202103301__update_invoices_table.sql
Unrecognised migration name format: v202101060__update_templates_table.sql
Unrecognised migration name format: v202103250__update_taxes_table.sql
Unrecognised migration name format: v202104210__update_cash_counts_table.sql
Unrecognised migration name format: v202104240__update_remissions_table.sql
Unrecognised migration name format: v202008240__update_stores_table.sql
Unrecognised migration name format: v202107110__update_products_table.sql
Unrecognised migration name format: v202103300__delete_updates_tables.sql
Unrecognised migration name format: v202007260__create_main_tables.sql
Unrecognised migration name format: v202108200__update_credit_notes_table.sql
Unrecognised migration name format: v202103180__update_app_web_updates_table.sql
Unrecognised migration name format: v202104230__update_purchase_orders_table.sql
Unrecognised migration name format: v202101110__update_credit_notes_table.sql
Unrecognised migration name format: v202009010__update_templates_table.sql
Unrecognised migration name format: v202105260__update_email_messages_table.sql
Unrecognised migration name format: v202008300__create_templates_table.sql
Unrecognised migration name format: v202101091__update_templates_table.sql
Unrecognised migration name format: v202011020__create_stats_tables.sql
Unrecognised migration name format: v202012300__update_invoices_table.sql
Unrecognised migration name format: v202107220__update_cash_receipts_table.sql
Unrecognised migration name format: v202007280__update_users_table.sql
Unrecognised migration name format: v202009091__update_app_installations_table.sql
Unrecognised migration name format: v202012310__update_credit_notes_table.sql
Unrecognised migration name format: v202111070__update_unused_tables.sql
Unrecognised migration name format: v202009090__update_stores_table.sql
Unrecognised migration name format: v202102130__update_invoices_table.sql
Unrecognised migration name format: v202102140__update_stats_templates_table.sql
Unrecognised migration name format: v202104030__update_invoice_resolutions_table.sql
Unrecognised migration name format: v202101090__delete_unused_tables.sql
Unrecognised migration name format: v202104110__update_invoices_detail_table.sql
Unrecognised migration name format: v202106031__update_app_stats_tables.sql
Unrecognised migration name format: v202106030__update_app_web_updates_table.sql
Unrecognised migration name format: v202205100__update_web_form_table.sql
Unrecognised migration name format: v202008230__update_taxes_table.sql
Unrecognised migration name format: v202108220__update_cash_counts_table.sql
Unrecognised migration name format: v202009100__update_services_table.sql
Unrecognised migration name format: v202102100__update_email_messages_table.sql
Unrecognised migration name format: v202007270__update_third_parties_tables.sql
Unrecognised migration name format: v202104020__update_auth_tables.sql
Unrecognised migration name format: v202104170__credit_notes_tables.sql
Unrecognised migration name format: v202104010__delete_app_templates_table.sql
Unrecognised migration name format: v202103280__update_third_parties_table.sql
Unrecognised migration name format: v202104160__update_auth_tables.sql
Unrecognised migration name format: v202106290__update_email_messages_table.sql
Unrecognised migration name format: v202107080__update_credit_notes_table.sql
Unrecognised migration name format: v202111090__update_contacts_table.sql
Unrecognised migration name format: v202012290__update_email_messages_table.sql
Unrecognised migration name format: v202101130__update_templates_table.sql
	at org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:59)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:144)
	at org.flywaydb.core.Flyway.repair(Flyway.java:330)
	at [hidden].apiDatabaseMigrations(Migrator.java:116)
        ...

Process finished with exit code 1

```

```java
    private void apiDatabaseMigrations() {
        DriverDataSource dds = new DriverDataSource(Thread.currentThread().getContextClassLoader(),
            "com.mysql.cj.jdbc.Driver",
            "jdbc:mysql://" + this.config.getHost() + ":" + this.config.getPort() + "/" + this.config.getDatabase() + this.config.getUrlProperties(),
            this.config.getUsername(),
            this.config.getPassword()
        );

        Flyway flyway = Flyway.configure()
            .baselineOnMigrate(true)
            .validateMigrationNaming(true)
            .dataSource(dds)
            .encoding("UTF-8")
            .installedBy("[HIDDEN]_MIGRATOR")
            .locations("migrations")
            .sqlMigrationPrefix("v")
            .sqlMigrationSeparator("__")
            .sqlMigrationSuffixes(".sql")
            .table("migrations")
            .load();

        flyway.repair();
        flyway.migrate();
    }
```

###### What did you expect to see?

What you would expect to see is all migrations checked and run like Flyway did before.

###### What did you see instead?

Migrations do not run due to a file name error.

**Comment by DoodleBobBuffPants** [comment]
In the JAR you're trying to execute there should be a service `org.flywaydb.core.extensibility.Plugin`
Could you share it's contents - this will let us know if the right services are listed

**Comment by DoodleBobBuffPants** [comment]
Upon further investigation, it seems that by default when you build into a single JAR one of the service files wins which you saw is affected by the dependency order (see [this StackOverflow](https://stackoverflow.com/a/66986906) answer)

You could try [this](https://stackoverflow.com/questions/31311299/maven-building-jar-merge-duplicate-resources-from-dependencies) approach for merging resources with Maven

**Comment by cristiammercado** [comment]
Hi,

I was doing some tests with the information you shared and I didn't know that Flyway used a service file that was being overwritten when I added the two dependencies `flyway-core` and `flyway-mysql`.

Since I use Maven and the `maven-shade-plugin` to generate the fat-jar, what I did was change a bit the behavior when it finds two files with the same name (in this case, `META-INF/services/org.flywaydb.core.extensibility.Plugin`). Both dependencies have this file and are overwritten depending on the order of the dependencies in the `pom.xml` file. The change I made was to add `AppendingTransformer`:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-shade-plugin</artifactId>
  <version>3.3.0</version>
  <executions>
      <execution>
          <phase>package</phase>
          <goals>
              <goal>shade</goal>
          </goals>
          <configuration>
              <transformers>
                  <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                      <resource>META-INF/services/org.flywaydb.core.extensibility.Plugin</resource>
                  </transformer>
              </transformers>
              <artifactSet/>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <outputFile>target/[hidden].jar</outputFile>
          </configuration>
      </execution>
  </executions>
</plugin>
```

With this change, the service file is complete and the content of the two files is concatenated:

![Screenshot_5](https://user-images.githubusercontent.com/4806666/179800365-0718c25a-031f-4d95-9b31-fccea090fe29.png)

Although it still seems a bit strange to me that before with the `flyway-core` dependency in a transitive way it worked and now it's time to add it explicitly.

In any case, the problem was solved, thank you very much for all the help and guidance.

**Comment by DoodleBobBuffPants** [comment]
Thanks for getting back to us to let us know - we're glad it's working now

If you think this is something we should document on our [website](https://flywaydb.org/documentation/) we'd like to know if you:

- tried to find guidance in the documentation (and if so, where)
- where you might expect to find this information on the website (if you'd expect to find it at all)

Thanks again :)

**Comment by Splitframe** [comment]
For People who use shadowJar:

```kotlin
tasks.withType<ShadowJar> {
    mergeServiceFiles {
        setPath("META-INF/services/org.flywaydb.core.extensibility.Plugin")
    }
}
```

**Comment by pruoff** [comment]
> Thanks for getting back to us to let us know - we're glad it's working now
> 
> If you think this is something we should document on our [website](https://flywaydb.org/documentation/) we'd like to know if you:
> 
> * tried to find guidance in the documentation (and if so, where)
> * where you might expect to find this information on the website (if you'd expect to find it at all)
> 
> Thanks again :)

@DoodleBobBuffPants 
It would have saved me at least one day of desperation if that info would have been on the documentation! I'd put it on the page for the Java API at https://documentation.red-gate.com/fd/api-java-184127629.html.

Searching for the "No database found to handle" one finds all kinds of resources stating that the db-package is missing from the pom. But only here the issue with the META-INF/services/org.flywaydb.core.extensibility.Plugin is addressed.

**Comment by grian32** [comment]
Still an issue btw ^^ Docs would be great @DoodleBobBuffPants , I got lucky and found this issue

**Comment by Braekpo1nt** [comment]
> Thanks for getting back to us to let us know - we're glad it's working now
> 
> If you think this is something we should document on our [website](https://flywaydb.org/documentation/) we'd like to know if you:
> 
> * tried to find guidance in the documentation (and if so, where)
> * where you might expect to find this information on the website (if you'd expect to find it at all)
> 
> Thanks again :)

I looked for information on this when referencing the [Database Driver Reference](https://documentation.red-gate.com/flyway/reference/database-driver-reference) docs, specifically the [MySQL](https://documentation.red-gate.com/flyway/reference/database-driver-reference/mysql) and [MariaDB](https://documentation.red-gate.com/flyway/reference/database-driver-reference/mariadb) pages. It would have been nice if it mentioned that some people have problems shading both the `flyway-core` and `flyway-mysql` dependencies into their Jars. 

I only figured out the issue because of a [discord post](https://discord.com/channels/289587909051416579/555462289851940864/1404802160377598032) that mentioned it for Minecraft Paper plugin development (in which developers frequently have to shade dependencies into a fat jar to get their plugins to work). For posterity, he mentions that for Shadow plugin 8.+ you use
```groovy
tasks.shadowJar {
    mergeServiceFiles()
}
// Or alternativaley only the flyway file
tasks.shadowJar {
  mergeServiceFiles {
    setPath("META-INF/services/org.flywaydb.core.extensibility.Plugin")
  }
}
```
or for Shadow plugin 9.+ you use:
```groovy
tasks.shadowJar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  mergeServiceFiles()
  filesMatching("META-INF/services/**") {
      duplicatesStrategy = DuplicatesStrategy.INCLUDE
  }
}
// Or alternativaley only the flyway file
tasks.shadowJar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  mergeServiceFiles {
    path = "META-INF/services/org.flywaydb.core.extensibility.Plugin"
  }
  filesMatching("META-INF/services/**") {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
  }
}
```
In Gradle projects.
