### ISSUE TITLE
Removed functions in 19.20.0 release break Spring Boot's use of flyway. 

### ISSUE THREAD

**Issue by bseeger** [flyway/flyway#3694]
###### Which version and edition of Flyway are you using?

Attempting to upgrade to 9.20.0, am using 9.19.4 successfully. 
Spring Boot 3.0.5 (also tried 3.1.0)

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, it's in the latest release. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

Postgres 14.7

###### Which operating system are you using?

Mac OSX

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Our project is based on Spring Boot 3.0.5

I tried to upgrade flyway library to latest minor release: 9.20.0. I am seeing this failure:  

```  Caused by: java.lang.NoSuchMethodError: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.oracleSqlplus(boolean)'
```

I understand that it's because that [method along with many others were removed](https://github.com/flyway/flyway/commit/5bda08d4b101b30ad6eb9c7ffd6b10a416d5f6ef#diff-af4e169b8f26dd1d2bdf77f2a097917b46acc3e326309ab88499c3e787659398L844). 

I want to note, too, that this issue I'm seeing is because Spring Boot hasn't adapted yet to this brand new change - they, of course, haven't had time.  

What I'm surprised about though is a breaking change in flyway in a _minor_ release. There are several functions not marked as deprecated that have been removed.  At least they weren't marked deprecated in the code that was removed.  (were they marked as deprecated somewhere and maybe I missed it??)

Mostly I wanted to let you know that this minor release has a large negative effect because it's a breaking change. 
 
###### What did you expect to see?

Didn't expect for a function to be removed from a minor release. I cannot upgrade to this change, because Spring Boot needs to update first.

**Comment by Idane** [comment]
This is also breaking on our project, if anyone needs to reproduce https://github.com/krud-dev/ostara/pull/584

**Comment by hjortling** [comment]
Same for us upgrading when org.flywaydb:flyway-core and org.flywaydb:flyway-database-oracle from 9.19.4 to 9.20.0 
Running on: 
Spring boot 3.1.0 ,
Oracle Database 19c

**Comment by Barry-RG** [comment]
Thank you for your update. Unfortunately since we do not directly develop the Spring Boot integration there may be a delay in fixing this issue. However, the `oracleSqlplus` is a Teams paid for feature not a free community feature which is what are supported by Spring Boot. As a result this is a surprise as to why they are including it.

**Comment by wilkinsona** [comment]
Spring Boot supports several Teams features. My memory's a little hazy but I believe we added support back in the Boxfuse days when @axelfontaine was leading the project.

We should only try to set a Teams feature if it has been configured by the user. For example, the `oracleSqlplus` plus method should only be called if the `spring.flyway.oracle-sqlplus` configuration property has been set. This is how we were able to support both the Teams and Community editions. Unfortunately, now that the method has been removed entirely, the method reference that we use (`map.from(properties.getOracleSqlplus()).to(configuration::oracleSqlplus);`) results in an exception even when the method won't actually be called. We should be able to avoid the problem by using a lambda expression instead [as we do in several places already](https://github.com/spring-projects/spring-boot/blob/cee73cebd4fa17e70cd6ce1728fc429f7b37cc40/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L164-L265).

**Comment by g-stone7** [comment]
This bug is blocking me from upgrading to Spring Boot 3.1.1 too

**Comment by roded** [comment]
Does flyway not follow semver?
Should we expect 'minor' (y in x.y.z) versions to include breaking changes?
Thanks

**Comment by chrootlogin** [comment]
Bug verfied! Downgrading to 9.19.4 helps. You should follow semver and don't put breaking changes in a minor version.

**Comment by joschi** [comment]
Should be fixed in https://github.com/spring-projects/spring-boot/releases/tag/v2.7.14 via https://github.com/spring-projects/spring-boot/issues/36029.

**Comment by asgarddesigns** [comment]
> Should be fixed in https://github.com/spring-projects/spring-boot/releases/tag/v2.7.14 via [spring-projects/spring-boot#36029](https://github.com/spring-projects/spring-boot/issues/36029).

There's also a 3.1.x release for those using it:

https://github.com/spring-projects/spring-boot/releases/tag/v3.1.2

**Comment by bratkartoffel** [comment]
I can confirm that this is fixed with spring boot 3.1.2, Thanks!

**Comment by bseeger** [comment]
I can confirm that the fix in Spring Boot 3.1.2 works for my setup as well. Thanks!

**Comment by botPotyo** [comment]
It is "fixed" as long as you don't want to use the oracleSqlPlus property. If you have the Teams version (we do) and want to make use of this property then the Spring code is still broken. The way to set this property when using flyway >9.20 is documented on this page under the API heading: https://documentation.red-gate.com/fd/oracle-sqlplus-184127520.html

I checked and the OracleConfigurationExtension class is available in the free version of the flyway-database-oracle library. So, Spring can make this update in their code without having to depend on the Teams version.

**Comment by wilkinsona** [comment]
> So, Spring can make this update in their code without having to depend on the Teams version.

[We've already done that for Spring Boot 3.2](https://github.com/spring-projects/spring-boot/issues/36364) (GA in November). Unfortunately, the breaking API changes make it prohibitively difficult for us to support Flyway 9.19 and earlier at the same time as 9.20 and we can't force an upgrade to Flyway 9.20 in a maintenance release of Spring Boot. The net of this is that property-based support for the relocated Oracle settings has to wait till a new Spring Boot minor. In the meantime, programmatic configuration through a `FlywayConfigurationCustomizer` is an option for those who wish to use Flyway 9.20 with Spring Boot 3.1 and earlier.

**Comment by botPotyo** [comment]
Thanks for the response @wilkinsona!
